project:
  type: website
  output-dir: docs

website:
  title: "LeftOver Data"
  site-url: https://www.leftoverdata.com
  description: "Pushin it up."
  navbar:
    right:
      - about.qmd
      - icon: rss
        href: index.xml
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme:
      - lux
      - brand
    css: styles.css



