project:
  type: website
  output-dir: docs

website:
  title: "LeftOver Data"
  site-url: https://leftoverdata.com
  description: "A placeholder for a blog about data science and analytics."
  navbar:
    right:
      - about.qmd
      - icon: rss
        href: index.xml
      - icon: github
        href: https://github.com/leftoverdata/leftoverdata.github.io
      - icon: chat-left-text
        href: https://bsky.app/profile/dancranford.bsky.social
format:
  html:
    theme:
      - lux
      - brand
    css: styles.css



